# Generated by Django 2.0.1 on 2018-01-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('decription', models.TextField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=6.99, max_digits=100, null=True)),
            ],
        ),
    ]
