# Generated by Django 2.0.1 on 2018-02-14 16:26

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import produits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'My Produits',
                'verbose_name_plural': 'My Produits',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/michel/zaly/static_cdn/protected'), upload_to=produits.models.download_media_location)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=19)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=6.99, max_digits=100, null=True)),
                ('publish', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], max_length=255)),
                ('managers', models.ManyToManyField(related_name='managers_produits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hd', 'HD'), ('sd', 'SD'), ('micro', 'Micro')], default='hd', max_length=20)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('width', models.CharField(blank=True, max_length=20, null=True)),
                ('media', models.ImageField(blank=True, height_field='height', null=True, upload_to=produits.models.thumbnail_location, width_field='width')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.Produit')),
            ],
        ),
        migrations.AddField(
            model_name='myproduits',
            name='produits',
            field=models.ManyToManyField(to='produits.Produit'),
        ),
        migrations.AddField(
            model_name='myproduits',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
