# Generated by Django 2.0.1 on 2018-02-16 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managers_produits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.DecimalField(decimal_places=3, default=77, max_digits=19),
        ),
    ]
