# Generated by Django 2.0.1 on 2018-02-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_auto_20180216_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='sale_active',
            field=models.BooleanField(default=False),
        ),
    ]
