# Generated by Django 2.0.1 on 2018-01-21 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_auto_20180120_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='decription',
            new_name='description',
        ),
    ]
