# Generated by Django 2.0.1 on 2018-01-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_auto_20180121_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
    ]
