# Generated by Django 2.0.1 on 2018-01-31 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produits', '0006_produit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='managers',
            field=models.ManyToManyField(related_name='managers_produits', to=settings.AUTH_USER_MODEL),
        ),
    ]
