# Generated by Django 2.0.1 on 2018-02-01 00:48

from django.db import migrations, models
import produits.models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_produit_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=produits.models.download_media_location),
        ),
    ]
